name: ci-test
on:
   push:
      branches: [ "main" ]
   pull_request:
      branches: [ "main" ]
jobs:
   build:
      runs-on: ${{ matrix.os }}
      permissions:
         contents: write
      strategy:
         fail-fast: false
         matrix:
            os: [ ubuntu-24.04 ]
      
      steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Pandoc
        run: |
         sudo apt update
         sudo apt -y install pandoc
         pandoc --version

      - name: Generate HTML files
        run: |
         mkdir -p items
         pandoc -f markdown -t html --template=src/templates/index-template.html --eol=lf --toc --no-highlight -V pagetitle="index.html" src/index.md > index.html
         for file in src/items/*.md; do
            filename=$(basename -- $file)
            filename="${filename%.*}.html"
            pandoc -f markdown -t html --template=src/templates/template.html --preserve-tabs --eol=lf --toc --no-highlight -V pagetitle="$filename" --mathjax "$file" > "items/$filename"
         done
         for file in src/items/with-katex/*.md; do
            filename=$(basename -- $file)
            filename="${filename%.*}.html"
            pandoc -f markdown -t html5 --template=src/templates/template-with-katex.html --preserve-tabs --eol=lf --toc --no-highlight -V pagetitle="$filename" --mathjax "$file" > "items/$filename"
         done
      
      - name: Deploy Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
         branch: gh-pages
         folder: . 
            
